version: 2

build:
  os: 'ubuntu-24.04'
  tools:
    # The Python version here must match the version set in `tox.ini`
    # to help ensure documentation builds are tested in a reproducible way.
    python: '3.13'

sphinx:
  configuration: 'documentation/conf.py'
  builder: 'html'
  fail_on_warning: true

python:
  install:
    - requirements: "requirements/docs/requirements.txt"
